### ISSUE TITLE
[BE] 제품 정보 삭제를 위한 관리자 페이지 구현

### ISSUE THREAD

**Issue by toneofrain** [codestates-seb/seb40_main_011#120]
## Description
제품 정보 삭제를 위한 관리자 페이지를 구현한다. 추후 유저 관리 등의 기능 추가 가능

## Todo
- [ ] 관리자 로그인 페이지 추가
- [ ] 관리자 로그인 기능 구현
- [ ] 관리자 페이지 레이아웃 추가
- [ ] 제품 정보 관리 페이지 추가
- [ ] 제품 삭제 기능 구현
