### ISSUE TITLE
[FE] login 및 signup 기능구현 및 css 외 기타

### ISSUE THREAD

**Issue by kwngmin** [codestates-seb/seb40_main_011#123]
## Description
login 및 signup 서버와 통신 기능 구현 css 외 기타

## Todo
- [x] login page 서버와의 통신 기능 구현
- [x] signup page 서버와의 통신 기능 구현
- [x] login page css 수정
- [x] signup page css 수정
- [x] icon 폴더 생성 및 파일 정렬
- [x] layout 폴더 생성 및 route에 각기 다른 layout을 route에 적용
- [x] pages 폴더에 index 생성 및 적용
