### ISSUE TITLE
[FE] token 관련된 이슈 및 기타

### ISSUE THREAD

**Issue by kwngmin** [codestates-seb/seb40_main_011#135]
## Description
token 저장 방식을 변경하였습니다.
로그인 및 회원가입 스타일을 수정하였습니다.
질문하기 기능을 추가했습니다.
정규식을 util 폴더에 별도로 관리합니다.

## Todo
- [x] login token 방식 변경
- [x] 로그인 및 회원가입 스타일 수정
- [x] 질문하기 기능 추가
- [x] 정규식 util 폴더에 별도 관리
- [x] 외 기타 소소한 변경(헤더, api, 모달 등)
