### ISSUE TITLE
[BE] 스낵리뷰 점수 유효성 검사 안 되는 문제 해결 및 리팩토링

### ISSUE THREAD

**Issue by toneofrain** [codestates-seb/seb40_main_011#181]
## Todo
- [x] 스낵리뷰 점수 유효성 검사 안 되는 문제 해결
- [x] 스낵리뷰 점수 유효성 검사 리팩토링
- [x] 제품 메인페이지 조회 리팩토링
