### ISSUE TITLE
[FE] 질문 page 기능추가 및 기타

### ISSUE THREAD

**Issue by kwngmin** [codestates-seb/seb40_main_011#202]
## Description
완성도를 높이기 위한 작업을 수행했습니다.

## Todo
- [x] selector 버튼 밖에 클릭하면 없애기
- [x] image가 null인 계정은 placeholder 보여주기
- [x] 회원가입할때 6종류 image에서 랜덤으로 지정하기
- [x] 질문에 댓글이 달리면 수정이 안되게 변경
- [x] 질문에 댓글이 달리면 삭제가 안되게 변경
- [x] 그외 자잘한 style 수정
