### ISSUE TITLE
[BE] 제품과 상세리뷰에 썸네일 기능 적용

### ISSUE THREAD

**Issue by INewWorldI** [codestates-seb/seb40_main_011#238]
## Description
제품과 상세 리뷰에 썸네일 기능을 적용합니다.

## Todo
- [ ] 제품과 상세리뷰에 썸네일 엔티티 추가
- [ ] 작성 및 수정 기능에 로직 구현
- [ ] 응답 데이터에 썸네일 데이터 추가 
- [ ] 구현 기능 테스트

**Comment by INewWorldI** [comment]
제품의 경우 썸네일 처리를 하지 않음
