### ISSUE TITLE
[BE] 제품 조회 기능 수정 및 응답 데이터 정리

### ISSUE THREAD

**Issue by INewWorldI** [codestates-seb/seb40_main_011#240]
## Description
잘못 구현된 제품의 조회 기능을 수정합니다.

## Todo
- [x] 제품 조회 기능 수정
- [x] 수정 기능 테스트
- [ ] 응답 데이터 수정
