### ISSUE TITLE
[BE] User 보안 없이 간단한 로직 구현

### ISSUE THREAD

**Issue by hea0408never** [codestates-seb/seb40_main_011#25]
## Description
회원가입, 정보수정 등 보안 없이 구현한다.

## Todo
- [x] 공용 exception 생성
- [x] 회원가입 구현
- [x] 내정보 수정 구현
- [x] 내정보 조회 구현
