### ISSUE TITLE
[FE] Main page 레이아웃 및 css, 기능 변경

### ISSUE THREAD

**Issue by kwngmin** [codestates-seb/seb40_main_011#252]
## Description
해당 페이지의 완성도를 높이기 위한 아래의 작업을 수행했습니다.

## Todo
- [ ] 반응형 페이지 적용
- [ ] 전체 레이아웃 변경
- [ ] 변경된 style 적용
- [ ] 더보기 기능 추가
- [ ] 페이지네이션 기능 제거
