### ISSUE TITLE
[BE] 파일 컨트롤러 리팩토링 및 검증

### ISSUE THREAD

**Issue by INewWorldI** [codestates-seb/seb40_main_011#266]
## Description
파일 컨트롤러에 파일 검증과 리팩토링을 진행해서 컨트롤러를 개선합니다.

## Todo
- [x] 파일 검증 구현
- [x] 파일 컨트롤러 리팩토링
- [x] 구현 기능 테스트
