### ISSUE TITLE
[BE] 스낵리뷰 컨트롤러 구현

### ISSUE THREAD

**Issue by toneofrain** [codestates-seb/seb40_main_011#29]
## Description
Mocking을 통해 더미데이터를 넘겨줄 수 있는 스낵리뷰 컨트롤러를 구현한다.

## Todo
- [x] 스낵리뷰 작성
- [x] 스낵리뷰 수정
- [x] 스낵리뷰 삭제
- [x] 스낵리뷰 최신순 조회
- [x] 스낵리뷰 평점높은순 조회
- [x] 스낵리뷰 평점낮은순 조회
