### ISSUE TITLE
[FE] fix: 리뷰 작성 페이지 수정

### ISSUE THREAD

**Issue by Heera1** [codestates-seb/seb40_main_011#293]
## Description
리뷰 작성 페이지 수정

## Todo
- [x] 응답으로 들어오는 게시글 id 로 리다이렉팅
- [x] 대분류 , 소분류 선택후 대분류 선택시 소분류가 선택되는 거 수정
- [x] 대분류 소분류 동시에 셀렉터 활성화 수정
- [x] 제품 추가 디테일 필수 요소임을 표시하기
