### ISSUE TITLE
[BE] JPA 최적화

### ISSUE THREAD

**Issue by toneofrain** [codestates-seb/seb40_main_011#30]
## Todo
- [x] 연관관계 편의메소드 수정
- [x] fetch 옵션 적용
- [x] casacade 옵션 적용
- [ ] 인덱스 적용
