### ISSUE TITLE
[FE] 리뷰 작성 페이지

### ISSUE THREAD

**Issue by Heera1** [codestates-seb/seb40_main_011#308]
## Description
리뷰 작성 페이지

## Todo
- [x] 게시글 작성 후에도 남아있는 소분류 값 초기화
- [x] 리뷰 본문이 300자가 넘었는데도 작성버튼 클릭시 300자 이상 작성하라고 모달창 뜨는 거 해결
- [x] 반응형 구현
- [ ] 제품 등록 모달창 대분류와 리뷰작성 대분류 분리하기
- [ ] 새로고침이나 다른 페이지 이동시 팝업창 띄우기
