### ISSUE TITLE
[FE] review list page css 외 기타

### ISSUE THREAD

**Issue by kwngmin** [codestates-seb/seb40_main_011#317]
## Description
웹사이트의 완성도를 높이기 위해 아래와 같은 작업을 하였습니다.

## Todo
- [ ] 회원가입 이메일 인증버튼 색상 변경
- [ ] 레이아웃에 메인 div 제거 및 root 배경색 추가
- [ ] 리뷰 리스트 페이지 전반적인 기능 재배치 및 스타일 변경
