### ISSUE TITLE
[FE] footer component 생성 및 css 구현

### ISSUE THREAD

**Issue by kwngmin** [codestates-seb/seb40_main_011#33]
## Description
pre project때 사용한 footer 재사용

## Todo
- [ ] 소스코드 복사 & 붙여넣기
- [ ] 이미지 복사 & 붙여넣기
- [ ] 팀원 및 팀 정보 수정
- [ ] 타입스크립트 변환
