### ISSUE TITLE
[BE] 스낵리뷰 엔티티 칼럼 추가 및 변경

### ISSUE THREAD

**Issue by toneofrain** [codestates-seb/seb40_main_011#34]
## Description
Score 칼럼을 JSON 타입으로 바꿀 수 있게끔 하고 정렬을 위한 Grade 칼럼 추가

## Todo
- [x] JSON을 매핑할 스낵리뷰 내부 클래스 Score 생성
- [x] JSON 컨버터 구현
- [x] Grade 칼럼 추가
- [x] Score에서 Grade 계산하는 로직 추가
