### ISSUE TITLE
[FE] header component 생성 및 css 구현

### ISSUE THREAD

**Issue by kwngmin** [codestates-seb/seb40_main_011#35]
## Description
간단한 요약을 써주세요

## Todo
- [ ] 소스코드 복사 & 붙여넣기
- [ ] 로고 이미지 삽입
- [ ] 검색바 기능 제한
- [ ] 타입스크립트 변환
- [ ] css 변경
