### ISSUE TITLE
[FE] 메인페이지 구현

### ISSUE THREAD

**Issue by EthanJcoding** [codestates-seb/seb40_main_011#41]
## Description
코드테크 메인페이지 구현입니다.

## Todo
- [x] 헤더, 푸터 완성 후 병합
- [x] 더미데이터에서 데이터 불러오기
- [x] 해당 데이터 가공하기
- [x] 헤더, 푸터 기능 구현
- [x] 레이아웃 완성하기
- [x] 베스트 리뷰 기능구현
- [x] 카테고리 기능구현
