### ISSUE TITLE
[TEAM] CI/CD 자동화 설정

### ISSUE THREAD

**Issue by INewWorldI** [codestates-seb/seb40_main_011#5]
## Description
프로젝트 개발에 CI/CD 자동화를 구축해서 활용한다.

## TODO
- [x] 젠킨스 설치
- [x] 도메인 설정 및 NGINX 프록시 설정
- [x] 기본 빌드 연결 테스트
- [x] 그래들 빌드 테스트
- [x] 리액트 빌드 테스트 
- [x] 그래들 자동 배포
- [x] 리액트 자동 배포
- [x] git 자동 배포 체크

**Comment by INewWorldI** [comment]
프론트 엔드와 추후에 협업이 필요함.

**Comment by INewWorldI** [comment]
일단 백엔드 팀에서는 자동 배포 확인 됨 ,
프론트랑 협업해서 리액트 배포도 체크해야 합니다!

**Comment by EthanJcoding** [comment]
<img width="1387" alt="스크린샷 2022-11-15 오후 3 29 55" src="https://user-images.githubusercontent.com/76644123/201843739-75b21cce-2c6d-4368-bbfd-faba56c82897.png">

프론트 확인 완료
