### ISSUE TITLE
[BE] 백엔드 자동 배포 보수 (데이터베이스 연결)

### ISSUE THREAD

**Issue by INewWorldI** [codestates-seb/seb40_main_011#50]
## Description
백엔드 자동 배포를 위한 여러가지 작업을 진행한다.

## Todo
- [x] 설정 파일 연결
- [x] 데이터베이스 연결 확인
- [ ] 폴더 생성 및 파일 저장 확인
